# Generated by Django 5.2.16 on 2026-09-18 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Stored separately so the trail remains after a user is deleted.', max_length=150)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('module_open', 'Opened module'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('export', 'Exported'), ('import', 'Imported'), ('backup', 'Backup'), ('restore', 'Restore'), ('other', 'Other')], db_index=True, max_length=20)),
                ('module', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'action'], name='core_auditt_created_8fbe73_idx'), models.Index(fields=['username', '-created_at'], name='core_auditt_usernam_5192e2_idx')],
            },
        ),
    ]
