# Generated by Django 5.2.16 on 2026-07-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('beneficiary_class', models.CharField(choices=[('Solo Parent', 'Solo Parent'), ('PWD', 'PWD'), ('Senior Citizen', 'Senior Citizen'), ('Construction Worker', 'Construction Worker'), ('Rice Farmer', 'Rice Farmer'), ('Market Vendor', 'Market Vendor'), ('Tricycle Driver', 'Tricycle Driver'), ('Lactating Mother', 'Lactating Mother')], max_length=60)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('rfid_id', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='RFID / ID Number')),
                ('is_active', models.BooleanField(default=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
