# Generated by Django 4.2.30 on 2026-07-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='prior_grant_date',
            field=models.DateField(blank=True, help_text='Date this person last received assistance from any program before being added to this system. Used to enforce the 3-month cooldown.', null=True, verbose_name='Last grant received (prior to registration)'),
        ),
    ]
