# Generated by Django 4.2.30 on 2026-07-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_familymember_member_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['relationship']},
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='signature',
            field=models.TextField(blank=True, default='', help_text="Beneficiary's signature captured on the ID form, stored as a PNG data URL and printed on the e-Bahagi ID card."),
        ),
    ]
