# Generated by Django 5.2.16 on 2026-09-18 08:23

from django.db import migrations, models


def backfill_sex(apps, schema_editor):
    Beneficiary = apps.get_model("beneficiaries", "Beneficiary")
    Citizen = apps.get_model("citizens", "Citizen")

    # Infer from class where obvious
    Beneficiary.objects.filter(sex="", beneficiary_class="Lactating Mother").update(sex="F")

    # Copy sex from matching citizen registry entries (same last + first name)
    citizen_sex = {}
    for c in Citizen.objects.exclude(sex="").only("last_name", "first_name", "sex"):
        key = (c.last_name.lower().strip(), c.first_name.lower().strip())
        if key not in citizen_sex:
            citizen_sex[key] = c.sex

    to_update = []
    for b in Beneficiary.objects.filter(sex="").iterator():
        sex = citizen_sex.get((b.last_name.lower().strip(), b.first_name.lower().strip()))
        if sex:
            b.sex = sex
            to_update.append(b)
    if to_update:
        Beneficiary.objects.bulk_update(to_update, ["sex"], batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0005_alter_familymember_options_beneficiary_signature"),
        ("citizens", "0006_barangay_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                verbose_name="Sex",
            ),
        ),
        migrations.RunPython(backfill_sex, noop_reverse),
    ]
