# Generated by Django 5.2.16 on 2026-09-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_no', models.CharField(blank=True, help_text='Auto-assigned if left blank (e.g. CR-2026-00001).', max_length=40, null=True, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced')], max_length=20)),
                ('philsys_id', models.CharField(blank=True, max_length=30, verbose_name='PhilSys ID (National ID)')),
                ('voter_id', models.CharField(blank=True, max_length=40, verbose_name="Voter's ID")),
                ('other_id_type', models.CharField(blank=True, max_length=60)),
                ('other_id_number', models.CharField(blank=True, max_length=60)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, verbose_name='House / Street address')),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased'), ('moved', 'Moved out')], default='active', max_length=20)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citizen Registry',
                'verbose_name_plural': 'Citizen Registry',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='citizens_ci_last_na_b8ce08_idx'), models.Index(fields=['barangay'], name='citizens_ci_baranga_fe7473_idx'), models.Index(fields=['status'], name='citizens_ci_status_aa4383_idx')],
            },
        ),
    ]
