# Generated by Django 5.2.16 on 2026-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='signature',
            field=models.TextField(blank=True, default='', help_text='Signature captured on the ID form, stored as a PNG data URL and printed on the e-Bahagi ID card.'),
        ),
    ]
