# Generated by Django 5.2.16 on 2026-09-18 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_citizen_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='citizen_attachments/%Y/%m/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='education',
            field=models.CharField(blank=True, choices=[('', '—'), ('no_formal', 'No formal education'), ('elementary', 'Elementary level'), ('elementary_grad', 'Elementary graduate'), ('jhs', 'Junior high school level'), ('jhs_grad', 'Junior high school graduate'), ('shs', 'Senior high school level'), ('shs_grad', 'Senior high school graduate'), ('vocational', 'Vocational / Technical'), ('college', 'College level'), ('college_grad', 'College graduate'), ('postgrad', 'Post-graduate')], max_length=40, verbose_name='Highest Educational Attainment'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='health_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='citizen',
            name='income_range',
            field=models.CharField(blank=True, choices=[('', '—'), ('0-15000', 'Php 0.00 – Php 15,000.00'), ('15001-30000', 'Php 15,001.00 – Php 30,000.00'), ('30001-50000', 'Php 30,001.00 – Php 50,000.00'), ('50001-80000', 'Php 50,001.00 – Php 80,000.00'), ('80001+', 'Php 80,001.00 and above')], max_length=20, verbose_name='Monthly Income Range'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='occupation_1',
            field=models.CharField(blank=True, choices=[('', '—'), ('farmer', 'Farmer'), ('fisherfolk', 'Fisherfolk'), ('laborer', 'Laborer / Construction'), ('vendor', 'Vendor / Retail'), ('driver', 'Driver'), ('domestic', 'Domestic helper'), ('government', 'Government employee'), ('private', 'Private employee'), ('self_employed', 'Self-employed'), ('ofw', 'OFW'), ('student', 'Student'), ('housewife', 'Housewife / Homemaker'), ('retired', 'Retired'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=40, verbose_name='Occupation 1'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='occupation_2',
            field=models.CharField(blank=True, choices=[('', '—'), ('farmer', 'Farmer'), ('fisherfolk', 'Fisherfolk'), ('laborer', 'Laborer / Construction'), ('vendor', 'Vendor / Retail'), ('driver', 'Driver'), ('domestic', 'Domestic helper'), ('government', 'Government employee'), ('private', 'Private employee'), ('self_employed', 'Self-employed'), ('ofw', 'OFW'), ('student', 'Student'), ('housewife', 'Housewife / Homemaker'), ('retired', 'Retired'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=40, verbose_name='Occupation 2'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='occupation_3',
            field=models.CharField(blank=True, choices=[('', '—'), ('farmer', 'Farmer'), ('fisherfolk', 'Fisherfolk'), ('laborer', 'Laborer / Construction'), ('vendor', 'Vendor / Retail'), ('driver', 'Driver'), ('domestic', 'Domestic helper'), ('government', 'Government employee'), ('private', 'Private employee'), ('self_employed', 'Self-employed'), ('ofw', 'OFW'), ('student', 'Student'), ('housewife', 'Housewife / Homemaker'), ('retired', 'Retired'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=40, verbose_name='Occupation 3'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='religion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='citizen',
            name='rfid_tag',
            field=models.CharField(blank=True, max_length=60, verbose_name='RFID Tag'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='vulnerable_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bldg / Hse / Unit No.'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='municipality',
            field=models.CharField(blank=True, default='Bacnotan', max_length=100),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='province',
            field=models.CharField(blank=True, default='La Union', max_length=100),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='registry_no',
            field=models.CharField(blank=True, help_text='Auto-assigned if left blank (e.g. CR-2026-00001).', max_length=40, null=True, unique=True, verbose_name='Citizen ID'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='suffix',
            field=models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=20, verbose_name='Ext. Name'),
        ),
        migrations.CreateModel(
            name='CitizenFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('relationship', models.CharField(blank=True, choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Grandparent', 'Grandparent'), ('Grandchild', 'Grandchild'), ('In-law', 'In-law'), ('Other', 'Other')], max_length=40, verbose_name='Relationship to HH')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='citizens.citizen')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_of', to='citizens.citizen', verbose_name='Citizen')),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Composition',
                'ordering': ['id'],
            },
        ),
    ]
