# Generated by Django 5.2.16 on 2026-09-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_citizen_attachment_citizen_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='barangay',
            field=models.CharField(blank=True, choices=[('Agtipal', 'Agtipal'), ('Arosip', 'Arosip'), ('Bacqui', 'Bacqui'), ('Bacsil', 'Bacsil'), ('Bagutot', 'Bagutot'), ('Ballogo', 'Ballogo'), ('Baroro', 'Baroro'), ('Bitalag', 'Bitalag'), ('Bulala', 'Bulala'), ('Burayoc', 'Burayoc'), ('Bussaoit', 'Bussaoit'), ('Cabaroan', 'Cabaroan'), ('Cabarsican', 'Cabarsican'), ('Cabugao', 'Cabugao'), ('Calautit', 'Calautit'), ('Carcarmay', 'Carcarmay'), ('Casiaman', 'Casiaman'), ('Galongen', 'Galongen'), ('Guinabang', 'Guinabang'), ('Legleg', 'Legleg'), ('Lisqueb', 'Lisqueb'), ('Mabanengbeng 1st', 'Mabanengbeng 1st'), ('Mabanengbeng 2nd', 'Mabanengbeng 2nd'), ('Maragayap', 'Maragayap'), ('Nagatiran', 'Nagatiran'), ('Nagsaraboan', 'Nagsaraboan'), ('Nagsimbaanan', 'Nagsimbaanan'), ('Nangalisan', 'Nangalisan'), ('Narra', 'Narra'), ('Ortega', 'Ortega'), ('Oya-oy', 'Oya-oy'), ('Paagan', 'Paagan'), ('Pandan', 'Pandan'), ('Pang-pang', 'Pang-pang'), ('Poblacion', 'Poblacion'), ('Quirino', 'Quirino'), ('Raois', 'Raois'), ('Salincob', 'Salincob'), ('San Martin', 'San Martin'), ('Santa Cruz', 'Santa Cruz'), ('Santa Rita', 'Santa Rita'), ('Sapilang', 'Sapilang'), ('Sayoan', 'Sayoan'), ('Sipulo', 'Sipulo'), ('Tammocalao', 'Tammocalao'), ('Ubbog', 'Ubbog'), ('Zaragosa', 'Zaragosa')], max_length=100, verbose_name='Barangay'),
        ),
    ]
