# Generated by Django 5.2.16 on 2026-09-18 08:08

from django.db import migrations, models

from citizens.barangays import BARANGAY_RENAMES, DEFAULT_BARANGAYS


def seed_barangays(apps, schema_editor):
    Barangay = apps.get_model("citizens", "Barangay")
    Citizen = apps.get_model("citizens", "Citizen")

    for name in DEFAULT_BARANGAYS:
        Barangay.objects.get_or_create(name=name, defaults={"is_active": True})

    for old, new in BARANGAY_RENAMES.items():
        Citizen.objects.filter(barangay=old).update(barangay=new)

    # Normalize ALL CAPS / mixed case to the official label when it matches.
    official_by_upper = {n.upper(): n for n in DEFAULT_BARANGAYS}
    for row in Citizen.objects.exclude(barangay="").iterator():
        mapped = official_by_upper.get((row.barangay or "").upper())
        if mapped and row.barangay != mapped:
            row.barangay = mapped
            row.save(update_fields=["barangay"])


def unseed_barangays(apps, schema_editor):
    Barangay = apps.get_model("citizens", "Barangay")
    Barangay.objects.filter(name__in=DEFAULT_BARANGAYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("citizens", "0004_barangay_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barangay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Barangay",
                "verbose_name_plural": "Barangays",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="citizen",
            name="barangay",
            field=models.CharField(
                blank=True,
                help_text="Select from the barangay list (manage list under Barangays).",
                max_length=100,
                verbose_name="Barangay",
            ),
        ),
        migrations.RunPython(seed_barangays, unseed_barangays),
    ]
