# Generated by Django 5.2.16 on 2026-09-18 08:17

from django.db import migrations, models

from citizens.barangays import DEFAULT_POPULATIONS


def seed_populations(apps, schema_editor):
    Barangay = apps.get_model("citizens", "Barangay")
    for name, pop in DEFAULT_POPULATIONS.items():
        Barangay.objects.filter(name=name).update(population=pop)


def clear_populations(apps, schema_editor):
    Barangay = apps.get_model("citizens", "Barangay")
    Barangay.objects.filter(name__in=DEFAULT_POPULATIONS.keys()).update(population=0)


class Migration(migrations.Migration):

    dependencies = [
        ("citizens", "0005_barangay_model_and_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="barangay",
            name="population",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Census / reference population used on the dashboard chart.",
            ),
        ),
        migrations.RunPython(seed_populations, clear_populations),
    ]
