# Generated by Django 5.2.16 on 2026-09-19 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0006_barangay_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.CharField(choices=[('R_THUMB', 'Right Thumb'), ('R_INDEX', 'Right Index'), ('R_MIDDLE', 'Right Middle'), ('R_RING', 'Right Ring'), ('R_LITTLE', 'Right Little'), ('L_THUMB', 'Left Thumb'), ('L_INDEX', 'Left Index'), ('L_MIDDLE', 'Left Middle'), ('L_RING', 'Left Ring'), ('L_LITTLE', 'Left Little')], max_length=12, verbose_name='Finger')),
                ('template_data', models.TextField(blank=True, default='', help_text='Template string or ID emitted by the fingerprint scanner. Used for matching at the ID / Fingerprint Tap station.', verbose_name='Fingerprint Template / ID')),
                ('image_data', models.TextField(blank=True, default='', help_text='Optional fingerprint image stored as a PNG data URL.', verbose_name='Fingerprint Image')),
                ('quality', models.PositiveSmallIntegerField(blank=True, help_text='Scanner quality score (0–100), if available.', null=True, verbose_name='Quality Score')),
                ('device_name', models.CharField(blank=True, max_length=120, verbose_name='Scanner Device')),
                ('is_primary', models.BooleanField(default=False, help_text='Preferred finger for quick lookup.', verbose_name='Primary Finger')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='citizens.citizen')),
            ],
            options={
                'verbose_name': 'Citizen Fingerprint',
                'verbose_name_plural': 'Citizen Fingerprints',
                'ordering': ['citizen_id', 'finger'],
                'indexes': [models.Index(fields=['template_data'], name='citizens_ci_templat_820c79_idx')],
                'constraints': [models.UniqueConstraint(fields=('citizen', 'finger'), name='uniq_citizen_finger')],
            },
        ),
    ]
