# Generated by Django 5.2.3 on 2026-09-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0007_citizen_fingerprint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='citizenfingerprint',
            constraint=models.UniqueConstraint(condition=models.Q(('template_data', ''), _negated=True), fields=('template_data',), name='uniq_citizen_fp_template_data'),
        ),
    ]
