# Generated by Django 5.2.3 on 2026-09-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0008_uniq_fingerprint_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('live_in', 'Common law / Live-in'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('annulled', 'Annulled'), ('divorced', 'Divorced')], max_length=20),
        ),
    ]
