# Generated by Django 4.2.30 on 2026-07-15 04:12

from django.db import migrations, models
import settings_mgmt.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=settings_mgmt.models.system_logo_upload_path)),
                ('alt_text', models.CharField(blank=True, default='Organization logo', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Logo',
                'verbose_name_plural': 'System Logo',
            },
        ),
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['key'], 'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
    ]
