# Generated by Django 5.2.3 on 2026-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_mgmt', '0002_systemlogo_alter_systemsetting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemlogo',
            options={'verbose_name': 'System Branding', 'verbose_name_plural': 'System Branding'},
        ),
        migrations.AddField(
            model_name='systemlogo',
            name='org_name',
            field=models.CharField(blank=True, default='Humanitarian Assistance Grant Management', help_text='Shown under the logo on the login page, header, and dashboard. Easy to change anytime.', max_length=200, verbose_name='Feature / organization name'),
        ),
    ]
